### ISSUE TITLE
A Little More Detail Please

### ISSUE THREAD

**Issue by devloprs** [Varying-Vagrant-Vagrants/vvv-multisite#13]
I followed all the instructions completely yet I don't see the new wpmu site anywhere in the dash. I see the src files and subsites in the vvv-multisite directory but no default wordpress install

A bit confused.

**Comment by jeremyfelt** [comment]
Hi @devloprs, I'm going to close this out and move the discussion to https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1070. This repository is not built to work with the new provisioning system yet and I'm not sure what the future of it should be.
