### ISSUE TITLE
rename to vvv-sites

### ISSUE THREAD

**Issue by cfoellmann** [Varying-Vagrant-Vagrants/vvv-multisite#7]
@jeremyfelt how about extending the scope of this repo to `vvv-sites`?
That way we can provide a more diverse set of sites

**Comment by LoreleiAurora** [comment]
I am currently working on a way to do this, at present a repo like this will be provisioned all or nothing (not ideal) for now this should be left as is or split into 4 repos.

**Comment by devloprs** [comment]
How to see this new site in vvv.dev. I see the new source files in vvv-multisite but no actual site up and running. Do I need to provision within that directory?

**Comment by jeremyfelt** [comment]
@cfoellmann @LoreleiAurora I'm going to close issues on this repository. Let's use https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1070 to discuss its future.
